name: I Should Buy a Boat Cat
link: http://knowyourmeme.com/memes/i-should-buy-a-boat-cat
default:
- ''
- I should buy a boat
aliases:
- newspaper-cat
- newspaper-realization-cat
- realization-cat
- buy-a-boat
- boat-cat
regexes:
- ()/?(.+ should buy .+)
