name: You Should Feel Bad
link: http://knowyourmeme.com/memes/your-musics-bad-and-you-should-feel-bad
default:
- Your meme is bad
- and you should feel bad
aliases:
- you-should-feel-bad
- feel-bad
regexes:
- (.+ bad)/?(.+ feel bad)
- ()/?(.*feel bad)
